---
title: "RECONNAISSANCE SOIL SURVEY OF THE BUSIA AREA"
subtitle: (quarter degree sheet No. 101)
description: "A soil sample dataset"
author: "J.R. Rachilo and D.O. Michieka"
date: "1991-01-15"
links:
- url: "https://edepot.wur.nl/493413"
categories: [observations]
---

The present soil survey is the eighth in series of "Reconnaissance Soil Surveys" with
multipurpose land evaluation. The survey covers one toposheet (101) at scale 1:100,000.
The survey area has a substantial variation in annual rainfall with a general increase
of rainfall northward and eastward away from the area bordering Lake Victoria. The drier
areas bordering Lake Victoria have only one rainy season viz:- March-May, whereas in the
wetter areas, the rainfall distribution is bimodal viz:- March-May and August-December
periods. The variation in rainfall to some extent reflects the land use pattern which varies
from mainly grazing with crop cultivation in the low rainfall areas to mainly crop cultivation
with grazing in the high rainfall areas.

The report shows that the general pattern of the soil resources is mainly determined
by the physiographic position, the kind of bedrock (parent material) and climate. Most of
the soils are strongly weathered and are generally acid in nature due to the leaching of the
bases. They are dominantly low in calcium, potassium and organic matter and hence
nitrogen.

