---
title: "Welcome to the Kenya Soil Survey"
format: html
page-layout: full
search: true
image: https://soilwiki.isric.org/collections/metadata:main/items/isric_10119
image-alt: "Impact of soil erosion on dryland ecosystems"
repo-actions: [edit, issue]

about:
  template: solana
  image-width: 32em
  id: hero-heading

listing:
  - id: reports
    contents:
    - /reports
    - "!reports/index.qmd"
    sort: "date desc"
    image-placeholder: ./img/soil-report.png
    type: grid
    categories: false
    sort-ui: false
    filter-ui: false
    max-items: 4
    feed: false
    
  - id: data
    contents: 
    - /data
    - "!data/index.qmd"
    image-placeholder: ./img/soil-dataset.png
    sort: "date desc"
    type: grid
    categories: false
    sort-ui: false
    filter-ui: false
    max-items: 4
    feed: false
---

<br><br>

::: {#hero-heading}
### Welcome to Kenia Soil Survey

The **Kenya Soil Survey (KSS)**, a department within [KALRO](https://www.kalro.org), provides authoritative soil information to support sustainable land management, agricultural planning, environmental monitoring, and national development.  
:::

Our mission is to generate, curate, and share high-quality soil data and knowledge for researchers, policymakers, farmers, and the public.


## Contents of this Site:

## [Data](data/index.qmd)

Access datasets collected from soil survey missions across Kenya. Predicted distribution of soil properties (soil maps) and Soil health indicators, such as erosion risk, fertility, crop suitability.

::: {#data}
:::

[Read more about data](data.qmd)

## [Reports](reports/index.qmd)

Learn about our methodologies and protocols through detailed documentation, including:

::: {#reports}
:::

[Read more about our soil data approach](docs.qmd)

## Our Commitment

The Kenya Soil Survey is committed to:
- Providing **open, high-quality soil information**  
- Supporting **evidence-based decision-making**  
- Advancing **soil science research** in Kenya  
- Enabling sustainable management of natural resources  

We hope this platform will be a valuable resource for everyone interested in Kenya’s soils.



## Start Exploring
Use the navigation menu to browse datasets, maps, documentation.

If you have questions or need support, feel free to contact the Kenya Soil Survey team at [soil@kalro.org](mailto:soil@kalro.org).

